### PR TITLE
create component list

### PR DESCRIPTION
**Pull request by 0xjwerb**
https://www.sparkfun.com/products/17719 - 8 channel wavelength sensor (light)  - (inside, bottom)
https://www.sparkfun.com/products/11050 - waterproof temp x2  - (inside, bottom in soil and. in water tank)
https://www.sparkfun.com/products/18345 - volatile organic sensor
https://www.sparkfun.com/products/15103 - particulate matter
https://www.sparkfun.com/products/13637 - soil moisture x2-3  - (inside, bottom)
https://www.sparkfun.com/products/14015 - addressable leds
https://www.sparkfun.com/products/16466 - temp, humidity, barometric pressure
https://www.sparkfun.com/products/15112 - co2, temp, humidity - (inside, bottom)
https://www.sparkfun.com/products/15805 - high precision temp
https://www.amazon.com/dp/B00KF7MVI2 - pwm fan (top)
https://www.amazon.com/dp/B07V9GF44J - piezoelectric humidifer

### CODE REVIEW

**Comment by PatrickJohnDavies** [comment]
What's your username in discord?

**Comment by 0xjwerb** [comment]
***@***.***
  
  
  
    
  

  
  
>

**Comment by 0xjwerb** [comment]
Jwerb#7587
  
  
  
    
  

  
  
>

**Comment by PatrickJohnDavies** [comment]
Ah nice. So you know all you need to use git for this. I'll add you as a collaborator so you can push.

**Pull request merged**
